Attribute VB_Name = "ApplicationProvider"
Public LogFilePath As String
Public Const LoggingEnabled As Boolean = True

Public TotalCalls As Integer
Public CallsMade As Integer
Public StartTime As Double


Public Function SetComplete(ByVal message As String) As Boolean
    frmProgress.Hide

    frmStatus.Show (0)
    
    frmStatus.lblStatus.Caption = message
    
    frmStatus.cmdExit.Enabled = True
    
    SetStatus (message)
    
    Do While frmStatus.Visible
        DoEvents
    Loop
End Function

Public Function SetError(Optional ByVal message As String) As Boolean
    frmProgress.Hide
    
    frmStatus.Show (0)
    
    Dim msg As String
    
    If Err.Number <> 0 Then
        
        msg = "Error # " & str(Err.Number) & " was generated by " _
             & Err.Source & Chr(13) & "Error Line: " & Erl & Chr(13) & Err.Description
             
        SetStatus (msg)
        
        MsgBox msg, , "Error", Err.HelpFile, Err.HelpContext
    Else
        SetStatus (message)
    End If
    
    SetComplete ("Error: " & message & vbCr & vbCr & "Log File: " & LogFilePath)
    
    Application.ScreenUpdating = True
    
    Application.ActiveWorkbook.Save
End Function

Public Function SetStatus(ByVal message As String) As Boolean
    If (LoggingEnabled = True) Then
        LogFilePath = Environ$("USERPROFILE") & "\My Documents\ecocalcs_log.txt"
        Dim logFile As TextStream
        Dim logFileObject As New FileSystemObject
    
        Set logFile = logFileObject.OpenTextFile(LogFilePath, ForAppending, True)
        
        logFile.WriteLine ("[" & Now & "]" & " " & message)
    End If
     
    'DoEvents
End Function

Public Function Sleep(Optional ByVal seconds As String = "08")
    Application.Wait (Now + TimeValue("0:00:" & seconds))
End Function

Public Function StartsWith(ByVal str As String, ByVal prefix As String) As Boolean
    StartsWith = Left(str, Len(prefix)) = prefix
End Function

Public Function UpdateProgress()
    Dim progress As Double
    Dim fraction As Double
    fraction = 100 / TotalCalls
        
    CallsMade = CallsMade + 1
    
    progress = Round(fraction * CallsMade, 0)
    
    If (progress >= 100) Then
        progress = 100
    End If

    frmProgress.Text.Caption = progress & "% Completed"
    frmProgress.Bar.Width = progress * 2
    frmProgress.Show (0)

    DoEvents
    
    If (progress >= 100) Then
        frmProgress.Text.Caption = "Finishing.."
    Else
        Sleep
    End If
End Function

Public Function GetTimeElapsed() As Double
   GetTimeElapsed = Round(Timer - StartTime, 2)
End Function

Public Function SetTimer()
    StartTime = Timer
End Function
